(* generated by dune *)

(** @canonical Merlin_kernel.Extension *)
module Extension = Merlin_kernel__Extension

(** @canonical Merlin_kernel.Mbrowse *)
module Mbrowse = Merlin_kernel__Mbrowse

(** @canonical Merlin_kernel.Mconfig *)
module Mconfig = Merlin_kernel__Mconfig

(** @canonical Merlin_kernel.Mconfig_dot *)
module Mconfig_dot = Merlin_kernel__Mconfig_dot

(** @canonical Merlin_kernel.Mocaml *)
module Mocaml = Merlin_kernel__Mocaml

(** @canonical Merlin_kernel.Mpipeline *)
module Mpipeline = Merlin_kernel__Mpipeline

(** @canonical Merlin_kernel.Mppx *)
module Mppx = Merlin_kernel__Mppx

(** @canonical Merlin_kernel.Mreader *)
module Mreader = Merlin_kernel__Mreader

(** @canonical Merlin_kernel.Mreader_explain *)
module Mreader_explain = Merlin_kernel__Mreader_explain

(** @canonical Merlin_kernel.Mreader_extend *)
module Mreader_extend = Merlin_kernel__Mreader_extend

(** @canonical Merlin_kernel.Mreader_lexer *)
module Mreader_lexer = Merlin_kernel__Mreader_lexer

(** @canonical Merlin_kernel.Mreader_parser *)
module Mreader_parser = Merlin_kernel__Mreader_parser

(** @canonical Merlin_kernel.Mreader_recover *)
module Mreader_recover = Merlin_kernel__Mreader_recover

(** @canonical Merlin_kernel.Msource *)
module Msource = Merlin_kernel__Msource

(** @canonical Merlin_kernel.Mtyper *)
module Mtyper = Merlin_kernel__Mtyper

(** @canonical Merlin_kernel.Phase_cache *)
module Phase_cache = Merlin_kernel__Phase_cache

(** @canonical Merlin_kernel.Pparse *)
module Pparse = Merlin_kernel__Pparse

(** @canonical Merlin_kernel.Standard_library *)
module Standard_library = Merlin_kernel__Standard_library
