(* generated by dune *)

(** @canonical Ocaml_utils.Build_path_prefix_map *)
module Build_path_prefix_map = Ocaml_utils__Build_path_prefix_map

(** @canonical Ocaml_utils.Clflags *)
module Clflags = Ocaml_utils__Clflags

(** @canonical Ocaml_utils.Compression *)
module Compression = Ocaml_utils__Compression

(** @canonical Ocaml_utils.Config *)
module Config = Ocaml_utils__Config

(** @canonical Ocaml_utils.Consistbl *)
module Consistbl = Ocaml_utils__Consistbl

(** @canonical Ocaml_utils.Diffing *)
module Diffing = Ocaml_utils__Diffing

(** @canonical Ocaml_utils.Diffing_with_keys *)
module Diffing_with_keys = Ocaml_utils__Diffing_with_keys

(** @canonical Ocaml_utils.Directory_content_cache *)
module Directory_content_cache = Ocaml_utils__Directory_content_cache

(** @canonical Ocaml_utils.Identifiable *)
module Identifiable = Ocaml_utils__Identifiable

(** @canonical Ocaml_utils.Lazy_backtrack *)
module Lazy_backtrack = Ocaml_utils__Lazy_backtrack

(** @canonical Ocaml_utils.Linkdeps *)
module Linkdeps = Ocaml_utils__Linkdeps

(** @canonical Ocaml_utils.Load_path *)
module Load_path = Ocaml_utils__Load_path

(** @canonical Ocaml_utils.Local_store *)
module Local_store = Ocaml_utils__Local_store

(** @canonical Ocaml_utils.Tbl *)
module Tbl = Ocaml_utils__Tbl

(** @canonical Ocaml_utils.Warnings *)
module Warnings = Ocaml_utils__Warnings
