(* generated by dune *)

(** @canonical Merlin_index_format.Index_cache *)
module Index_cache = Merlin_index_format__Index_cache

(** @canonical Merlin_index_format.Index_format *)
module Index_format = Merlin_index_format__Index_format

(** @canonical Merlin_index_format.Union_find *)
module Union_find = Merlin_index_format__Union_find
