(* generated by dune *)

(** @canonical Merlin_utils.File_cache *)
module File_cache = Merlin_utils__File_cache

(** @canonical Merlin_utils.File_id *)
module File_id = Merlin_utils__File_id

(** @canonical Merlin_utils.Format_doc *)
module Format_doc = Merlin_utils__Format_doc

(** @canonical Merlin_utils.Lib_config *)
module Lib_config = Merlin_utils__Lib_config

(** @canonical Merlin_utils.Logger *)
module Logger = Merlin_utils__Logger

(** @canonical Merlin_utils.Marg *)
module Marg = Merlin_utils__Marg

(** @canonical Merlin_utils.Misc *)
module Misc = Merlin_utils__Misc

(** @canonical Merlin_utils.Ppxsetup *)
module Ppxsetup = Merlin_utils__Ppxsetup

(** @canonical Merlin_utils.Sexp *)
module Sexp = Merlin_utils__Sexp

(** @canonical Merlin_utils.Stamped_hashtable *)
module Stamped_hashtable = Merlin_utils__Stamped_hashtable

(** @canonical Merlin_utils.Std *)
module Std = Merlin_utils__Std
