(* generated by dune *)

(** @canonical Ocaml_typing.Annot *)
module Annot = Ocaml_typing__Annot

(** @canonical Ocaml_typing.Btype *)
module Btype = Ocaml_typing__Btype

(** @canonical Ocaml_typing.Cmi_cache *)
module Cmi_cache = Ocaml_typing__Cmi_cache

(** @canonical Ocaml_typing.Cmi_format *)
module Cmi_format = Ocaml_typing__Cmi_format

(** @canonical Ocaml_typing.Cmt_cache *)
module Cmt_cache = Ocaml_typing__Cmt_cache

(** @canonical Ocaml_typing.Cmt_format *)
module Cmt_format = Ocaml_typing__Cmt_format

(** @canonical Ocaml_typing.Ctype *)
module Ctype = Ocaml_typing__Ctype

(** @canonical Ocaml_typing.Datarepr *)
module Datarepr = Ocaml_typing__Datarepr

(** @canonical Ocaml_typing.Env *)
module Env = Ocaml_typing__Env

(** @canonical Ocaml_typing.Envaux *)
module Envaux = Ocaml_typing__Envaux

(** @canonical Ocaml_typing.Errortrace *)
module Errortrace = Ocaml_typing__Errortrace

(** @canonical Ocaml_typing.Errortrace_report *)
module Errortrace_report = Ocaml_typing__Errortrace_report

(** @canonical Ocaml_typing.Ident *)
module Ident = Ocaml_typing__Ident

(** @canonical Ocaml_typing.Includeclass *)
module Includeclass = Ocaml_typing__Includeclass

(** @canonical Ocaml_typing.Includecore *)
module Includecore = Ocaml_typing__Includecore

(** @canonical Ocaml_typing.Includemod *)
module Includemod = Ocaml_typing__Includemod

(** @canonical Ocaml_typing.Includemod_errorprinter *)
module Includemod_errorprinter = Ocaml_typing__Includemod_errorprinter

(** @canonical Ocaml_typing.Lambda *)
module Lambda = Ocaml_typing__Lambda

(** @canonical Ocaml_typing.Magic_numbers *)
module Magic_numbers = Ocaml_typing__Magic_numbers

(** @canonical Ocaml_typing.Msupport *)
module Msupport = Ocaml_typing__Msupport

(** @canonical Ocaml_typing.Mtype *)
module Mtype = Ocaml_typing__Mtype

(** @canonical Ocaml_typing.Natural *)
module Natural = Ocaml_typing__Natural

(** @canonical Ocaml_typing.Oprint *)
module Oprint = Ocaml_typing__Oprint

(** @canonical Ocaml_typing.Out_type *)
module Out_type = Ocaml_typing__Out_type

(** @canonical Ocaml_typing.Outcometree *)
module Outcometree = Ocaml_typing__Outcometree

(** @canonical Ocaml_typing.Parmatch *)
module Parmatch = Ocaml_typing__Parmatch

(** @canonical Ocaml_typing.Path *)
module Path = Ocaml_typing__Path

(** @canonical Ocaml_typing.Patterns *)
module Patterns = Ocaml_typing__Patterns

(** @canonical Ocaml_typing.Persistent_env *)
module Persistent_env = Ocaml_typing__Persistent_env

(** @canonical Ocaml_typing.Predef *)
module Predef = Ocaml_typing__Predef

(** @canonical Ocaml_typing.Primitive *)
module Primitive = Ocaml_typing__Primitive

(** @canonical Ocaml_typing.Printpat *)
module Printpat = Ocaml_typing__Printpat

(** @canonical Ocaml_typing.Printtyp *)
module Printtyp = Ocaml_typing__Printtyp

(** @canonical Ocaml_typing.Printtyped *)
module Printtyped = Ocaml_typing__Printtyped

(** @canonical Ocaml_typing.Rawprinttyp *)
module Rawprinttyp = Ocaml_typing__Rawprinttyp

(** @canonical Ocaml_typing.Saved_parts *)
module Saved_parts = Ocaml_typing__Saved_parts

(** @canonical Ocaml_typing.Shape *)
module Shape = Ocaml_typing__Shape

(** @canonical Ocaml_typing.Shape_reduce *)
module Shape_reduce = Ocaml_typing__Shape_reduce

(** @canonical Ocaml_typing.Short_paths *)
module Short_paths = Ocaml_typing__Short_paths

(** @canonical Ocaml_typing.Short_paths_graph *)
module Short_paths_graph = Ocaml_typing__Short_paths_graph

(** @canonical Ocaml_typing.Signature_group *)
module Signature_group = Ocaml_typing__Signature_group

(** @canonical Ocaml_typing.Stypes *)
module Stypes = Ocaml_typing__Stypes

(** @canonical Ocaml_typing.Subst *)
module Subst = Ocaml_typing__Subst

(** @canonical Ocaml_typing.Tast_iterator *)
module Tast_iterator = Ocaml_typing__Tast_iterator

(** @canonical Ocaml_typing.Tast_mapper *)
module Tast_mapper = Ocaml_typing__Tast_mapper

(** @canonical Ocaml_typing.Type_immediacy *)
module Type_immediacy = Ocaml_typing__Type_immediacy

(** @canonical Ocaml_typing.Typeclass *)
module Typeclass = Ocaml_typing__Typeclass

(** @canonical Ocaml_typing.Typecore *)
module Typecore = Ocaml_typing__Typecore

(** @canonical Ocaml_typing.Typedecl *)
module Typedecl = Ocaml_typing__Typedecl

(** @canonical Ocaml_typing.Typedecl_immediacy *)
module Typedecl_immediacy = Ocaml_typing__Typedecl_immediacy

(** @canonical Ocaml_typing.Typedecl_properties *)
module Typedecl_properties = Ocaml_typing__Typedecl_properties

(** @canonical Ocaml_typing.Typedecl_separability *)
module Typedecl_separability = Ocaml_typing__Typedecl_separability

(** @canonical Ocaml_typing.Typedecl_unboxed *)
module Typedecl_unboxed = Ocaml_typing__Typedecl_unboxed

(** @canonical Ocaml_typing.Typedecl_variance *)
module Typedecl_variance = Ocaml_typing__Typedecl_variance

(** @canonical Ocaml_typing.Typedtree *)
module Typedtree = Ocaml_typing__Typedtree

(** @canonical Ocaml_typing.Typemod *)
module Typemod = Ocaml_typing__Typemod

(** @canonical Ocaml_typing.Typeopt *)
module Typeopt = Ocaml_typing__Typeopt

(** @canonical Ocaml_typing.Types *)
module Types = Ocaml_typing__Types

(** @canonical Ocaml_typing.Typetexp *)
module Typetexp = Ocaml_typing__Typetexp

(** @canonical Ocaml_typing.Untypeast *)
module Untypeast = Ocaml_typing__Untypeast

(** @canonical Ocaml_typing.Value_rec_check *)
module Value_rec_check = Ocaml_typing__Value_rec_check

(** @canonical Ocaml_typing.Value_rec_types *)
module Value_rec_types = Ocaml_typing__Value_rec_types
