(* generated by dune *)

(** @canonical Merlin_extend.Extend_driver *)
module Extend_driver = Merlin_extend__Extend_driver

(** @canonical Merlin_extend.Extend_main *)
module Extend_main = Merlin_extend__Extend_main

(** @canonical Merlin_extend.Extend_protocol *)
module Extend_protocol = Merlin_extend__Extend_protocol
