(* generated by dune *)

(** @canonical Odoc_search.Entry *)
module Entry = Odoc_search__Entry

(** @canonical Odoc_search.Html *)
module Html = Odoc_search__Html

(** @canonical Odoc_search.Text *)
module Text = Odoc_search__Text
