(* generated by dune *)

(** @canonical Ocaml_preprocess.Lexer_ident *)
module Lexer_ident = Ocaml_preprocess__Lexer_ident

(** @canonical Ocaml_preprocess.Lexer_raw *)
module Lexer_raw = Ocaml_preprocess__Lexer_raw

(** @canonical Ocaml_preprocess.MenhirLib *)
module MenhirLib = Ocaml_preprocess__MenhirLib

(** @canonical Ocaml_preprocess.Parser_explain *)
module Parser_explain = Ocaml_preprocess__Parser_explain

(** @canonical Ocaml_preprocess.Parser_printer *)
module Parser_printer = Ocaml_preprocess__Parser_printer

(** @canonical Ocaml_preprocess.Parser_raw *)
module Parser_raw = Ocaml_preprocess__Parser_raw

(** @canonical Ocaml_preprocess.Parser_recover *)
module Parser_recover = Ocaml_preprocess__Parser_recover
