(* generated by dune *)

(** @canonical Fiber.Cancel *)
module Cancel = Fiber__Cancel

(** @canonical Fiber.Core *)
module Core = Fiber__Core

(** @canonical Fiber.Mutex *)
module Mutex = Fiber__Mutex

(** @canonical Fiber.Mvar *)
module Mvar = Fiber__Mvar

(** @canonical Fiber.Pool *)
module Pool = Fiber__Pool

(** @canonical Fiber.Scheduler *)
module Scheduler = Fiber__Scheduler

(** @canonical Fiber.Stream *)
module Stream = Fiber__Stream

(** @canonical Fiber.Svar *)
module Svar = Fiber__Svar

(** @canonical Fiber.Throttle *)
module Throttle = Fiber__Throttle

module Fiber__ = struct end
[@@deprecated "this module is shadowed"]
