(* generated by dune *)

(** @canonical Merlin_sherlodoc.Name_cost *)
module Name_cost = Merlin_sherlodoc__Name_cost

(** @canonical Merlin_sherlodoc.Query *)
module Query = Merlin_sherlodoc__Query

(** @canonical Merlin_sherlodoc.Type_distance *)
module Type_distance = Merlin_sherlodoc__Type_distance

(** @canonical Merlin_sherlodoc.Type_expr *)
module Type_expr = Merlin_sherlodoc__Type_expr

(** @canonical Merlin_sherlodoc.Type_lexer *)
module Type_lexer = Merlin_sherlodoc__Type_lexer

(** @canonical Merlin_sherlodoc.Type_parsed *)
module Type_parsed = Merlin_sherlodoc__Type_parsed

(** @canonical Merlin_sherlodoc.Type_parser *)
module Type_parser = Merlin_sherlodoc__Type_parser

(** @canonical Merlin_sherlodoc.Type_polarity *)
module Type_polarity = Merlin_sherlodoc__Type_polarity
