(* generated by dune *)

(** @canonical Lsp.Array_view *)
module Array_view = Lsp__Array_view

(** @canonical Lsp.Cancel_request *)
module Cancel_request = Lsp__Cancel_request

(** @canonical Lsp.Cli *)
module Cli = Lsp__Cli

(** @canonical Lsp.Client_notification *)
module Client_notification = Lsp__Client_notification

(** @canonical Lsp.Client_request *)
module Client_request = Lsp__Client_request

(** @canonical Lsp.Diff *)
module Diff = Lsp__Diff

(** @canonical Lsp.Extension *)
module Extension = Lsp__Extension

(** @canonical Lsp.Header *)
module Header = Lsp__Header

(** @canonical Lsp.Import *)
module Import = Lsp__Import

(** @canonical Lsp.Io *)
module Io = Lsp__Io

(** @canonical Lsp.Position *)
module Position = Lsp__Position

(** @canonical Lsp.Progress *)
module Progress = Lsp__Progress

(** @canonical Lsp.Server_notification *)
module Server_notification = Lsp__Server_notification

(** @canonical Lsp.Server_request *)
module Server_request = Lsp__Server_request

(** @canonical Lsp.Snippet *)
module Snippet = Lsp__Snippet

(** @canonical Lsp.String_zipper *)
module String_zipper = Lsp__String_zipper

(** @canonical Lsp.Substring *)
module Substring = Lsp__Substring

(** @canonical Lsp.Text_document *)
module Text_document = Lsp__Text_document

(** @canonical Lsp.Types *)
module Types = Lsp__Types

(** @canonical Lsp.Uri0 *)
module Uri0 = Lsp__Uri0

(** @canonical Lsp.Uri_lexer *)
module Uri_lexer = Lsp__Uri_lexer
