(* generated by dune *)

(** @canonical Merlin_commands.New_commands *)
module New_commands = Merlin_commands__New_commands

(** @canonical Merlin_commands.Query_json *)
module Query_json = Merlin_commands__Query_json
